# mariadb-configmap
# db config설정값을 여기서 관리
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    max_connections=200
    # 추가적인 설정 값을 여기에 추가
