apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-np
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32000
  selector:
    app: mariadb