apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: chat
  labels:
    app: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: docker.redpanda.com/redpandadata/redpanda:latest
        command:
        - /usr/bin/rpk
        - redpanda
        - start
        - --mode
        - dev-container
        - --kafka-addr
        - 0.0.0.0:9092
        - --advertise-kafka-addr
        - redpanda.chat.svc.cluster.local:9092
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 8081
          name: schema-registry
        - containerPort: 8082
          name: proxy
        - containerPort: 9644
          name: admin
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: chat
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  - port: 9644
    targetPort: 9644
    name: admin
  selector:
    app: redpanda
