apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
      - name: redpanda-console
        image: docker.redpanda.com/redpandadata/console:latest
        env:
        - name: KAFKA_BROKERS
          value: "redpanda.chat.svc.cluster.local:9092"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  namespace: chat
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: redpanda-console
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redpanda-console-ingress
  namespace: chat
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - redpanda.cn.openmaru-beom.local
  rules:
  - host: redpanda.cn.openmaru-beom.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redpanda-console
            port:
              number: 80
