apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: chat
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:18.1-alpine3.23
        env:
        - name: POSTGRES_DB
          value: "chat_db"
        - name: POSTGRES_PASSWORD
          value: "temp_password"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql
  volumeClaimTemplates: 
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client" # sc 확인 필요
      resources:
        requests:
          storage: 1Gi 
