apiVersion: v1
kind: Service
metadata:
  name: k-django-svc
spec:
  selector:
    app: k-django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  
  type: ClusterIP


---
# nodeport -> 서비스 오픈
kind: Service
metadata:
  labels:
    app: k-django
  name: k-django-np
  namespace: default
spec:
  ports:
  - nodePort: 31858
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: k-django
  type: NodePort

