# 현재 docker image 테스트 후 배포
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k-django
  name: k-django
spec:
  replicas: 2 # 각 노드별 배포
  selector:
    matchLabels:
      app: k-django
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k-django
    spec:
      containers:
      - image: beomzh/pmc
        name: django
        ports:
        - containerPort: 8000
        resources: 
          requests:
            cpu: "500m"  # 0.5 CPU
            memory: "256Mi"
          limits:
            cpu: "1000m"  # 1 CPU
            memory: "512Mi"
      imagePullSecrets: 
      - name:  myregistrykey # 생성 예정
status: {}
